from coldfront.config.settings import ENV


UNIX_GROUP_ATTRIBUTE_NAME = ENV.str("UNIX_GROUP_ATTRIBUTE_NAME", "ad_group")
USER_MANAGEMENT_ENABLE_SIGNALS = ENV.bool("USER_MANAGEMENT_ENABLE_SIGNALS", False)
MANAGE_GROUPS_AT_PROJECT_LEVEL = ENV.bool("MANAGE_GROUPS_AT_PROJECT_LEVEL", False)
USER_MANAGEMENT_REMOVE_USERS_ON_PROJECT_ARCHIVE = ENV.bool("USER_MANAGEMENT_REMOVE_USERS_ON_PROJECT_ARCHIVE", False)
USER_MANAGEMENT_CLIENT_PATH = ENV.str("USER_MANAGEMENT_CLIENT_PATH", "user_management.grouper_user_management_client.UserManagementClient")