from coldfront.config.base import INSTALLED_APPS
from coldfront.config.env import ENV

INSTALLED_APPS += ["user_management"]


UNIX_GROUP_ATTRIBUTE_NAME = ENV.str("UNIX_GROUP_ATTRIBUTE_NAME")
USER_MANAGEMENT_CLIENT_PATH = ENV.str("USER_MANAGEMENT_CLIENT_PATH")
USER_MANAGEMENT_ENABLE_SIGNALS = ENV.bool("USER_MANAGEMENT_ENABLE_SIGNALS")
MANAGE_GROUPS_AT_PROJECT_LEVEL = ENV.bool("MANAGE_GROUPS_AT_PROJECT_LEVEL")
USER_MANAGEMENT_REMOVE_USERS_ON_PROJECT_ARCHIVE = ENV.bool("USER_MANAGEMENT_REMOVE_USERS_ON_PROJECT_ARCHIVE")
